// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"sync"
)

// Ensure, that rttAPIMock does implement rttAPI.
// If this is not the case, regenerate this file with moq.
var _ rttAPI = &rttAPIMock{}

// rttAPIMock is a mock implementation of rttAPI.
//
//	func TestSomethingThatUsesrttAPI(t *testing.T) {
//
//		// make and configure a mocked rttAPI
//		mockedrttAPI := &rttAPIMock{
//			GetServiceFunc: func(uid string, date string) (*ServiceResponse, error) {
//				panic("mock out the GetService method")
//			},
//			SearchDeparturesFunc: func(crs string, date string, fromTime string) (*SearchResponse, error) {
//				panic("mock out the SearchDepartures method")
//			},
//		}
//
//		// use mockedrttAPI in code that requires rttAPI
//		// and then make assertions.
//
//	}
type rttAPIMock struct {
	// GetServiceFunc mocks the GetService method.
	GetServiceFunc func(uid string, date string) (*ServiceResponse, error)

	// SearchDeparturesFunc mocks the SearchDepartures method.
	SearchDeparturesFunc func(crs string, date string, fromTime string) (*SearchResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetService holds details about calls to the GetService method.
		GetService []struct {
			// UID is the uid argument value.
			UID string
			// Date is the date argument value.
			Date string
		}
		// SearchDepartures holds details about calls to the SearchDepartures method.
		SearchDepartures []struct {
			// Crs is the crs argument value.
			Crs string
			// Date is the date argument value.
			Date string
			// FromTime is the fromTime argument value.
			FromTime string
		}
	}
	lockGetService       sync.RWMutex
	lockSearchDepartures sync.RWMutex
}

// GetService calls GetServiceFunc.
func (mock *rttAPIMock) GetService(uid string, date string) (*ServiceResponse, error) {
	if mock.GetServiceFunc == nil {
		panic("rttAPIMock.GetServiceFunc: method is nil but rttAPI.GetService was just called")
	}
	callInfo := struct {
		UID  string
		Date string
	}{
		UID:  uid,
		Date: date,
	}
	mock.lockGetService.Lock()
	mock.calls.GetService = append(mock.calls.GetService, callInfo)
	mock.lockGetService.Unlock()
	return mock.GetServiceFunc(uid, date)
}

// GetServiceCalls gets all the calls that were made to GetService.
// Check the length with:
//
//	len(mockedrttAPI.GetServiceCalls())
func (mock *rttAPIMock) GetServiceCalls() []struct {
	UID  string
	Date string
} {
	var calls []struct {
		UID  string
		Date string
	}
	mock.lockGetService.RLock()
	calls = mock.calls.GetService
	mock.lockGetService.RUnlock()
	return calls
}

// SearchDepartures calls SearchDeparturesFunc.
func (mock *rttAPIMock) SearchDepartures(crs string, date string, fromTime string) (*SearchResponse, error) {
	if mock.SearchDeparturesFunc == nil {
		panic("rttAPIMock.SearchDeparturesFunc: method is nil but rttAPI.SearchDepartures was just called")
	}
	callInfo := struct {
		Crs      string
		Date     string
		FromTime string
	}{
		Crs:      crs,
		Date:     date,
		FromTime: fromTime,
	}
	mock.lockSearchDepartures.Lock()
	mock.calls.SearchDepartures = append(mock.calls.SearchDepartures, callInfo)
	mock.lockSearchDepartures.Unlock()
	return mock.SearchDeparturesFunc(crs, date, fromTime)
}

// SearchDeparturesCalls gets all the calls that were made to SearchDepartures.
// Check the length with:
//
//	len(mockedrttAPI.SearchDeparturesCalls())
func (mock *rttAPIMock) SearchDeparturesCalls() []struct {
	Crs      string
	Date     string
	FromTime string
} {
	var calls []struct {
		Crs      string
		Date     string
		FromTime string
	}
	mock.lockSearchDepartures.RLock()
	calls = mock.calls.SearchDepartures
	mock.lockSearchDepartures.RUnlock()
	return calls
}
