package main

import "strings"

// Station holds a CRS code and its display name.
type Station struct {
	CRS  string `json:"crs"`
	Name string `json:"name"`
}

// stations is a list of UK rail stations ordered by name.
var stations = []Station{
	{"ABD", "Aberdeen"},
	{"ABW", "Abergavenny"},
	{"ABI", "Abingdon"},
	{"ACN", "Accrington"},
	{"ADV", "Adwick"},
	{"AGT", "Ainsdale"},
	{"AIN", "Aintree"},
	{"ALF", "Alfreton"},
	{"ALM", "Almouth"},
	{"ALN", "Alnmouth"},
	{"ALS", "Alsager"},
	{"ALT", "Alton"},
	{"ALV", "Alvechurch"},
	{"AML", "Ammanford"},
	{"ANC", "Ancaster"},
	{"AND", "Andover"},
	{"ANF", "Anfield"},
	{"ANG", "Angmering"},
	{"ANS", "Ansdell & Fairhaven"},
	{"APD", "Apperley Bridge"},
	{"APF", "Appledore"},
	{"ARD", "Ardrossan"},
	{"ARL", "Arlesey"},
	{"ARN", "Arnside"},
	{"ARR", "Arrochar & Tarbet"},
	{"ART", "Arundel"},
	{"ARU", "Arundel"},
	{"ASC", "Ascot"},
	{"ASF", "Ashford International"},
	{"ASH", "Ashford (Kent)"},
	{"ASK", "Askam"},
	{"ASN", "Aston"},
	{"ASP", "Aspatria"},
	{"ASS", "Ashurst New Forest"},
	{"AST", "Astley Bridge"},
	{"ATC", "Atcham"},
	{"ATH", "Atherton"},
	{"AUW", "Aughton Park"},
	{"AVM", "Aviemore"},
	{"AVN", "Avonmouth"},
	{"AYH", "Aylesham"},
	{"AYL", "Aylesbury"},
	{"AYP", "Aylesbury Vale Parkway"},
	{"AYR", "Ayr"},
	{"BAB", "Bamber Bridge"},
	{"BAD", "Baddeley Green"},
	{"BAG", "Baglan"},
	{"BAH", "Bath Spa"},
	{"BAI", "Baildon"},
	{"BAK", "Baker Street"},
	{"BAL", "Balham"},
	{"BAN", "Banbury"},
	{"BAR", "Barrow-in-Furness"},
	{"BAS", "Basingstoke"},
	{"BAT", "Bath"},
	{"BAW", "Bawley"},
	{"BBN", "Blackburn"},
	{"BBW", "Bamber Bridge"},
	{"BCH", "Birchwood"},
	{"BCK", "Blackrock"},
	{"BCN", "Beacon Hill"},
	{"BCU", "Buckshaw Parkway"},
	{"BDI", "Bradford Interchange"},
	{"BDM", "Bridgend"},
	{"BDN", "Bordeaux"},
	{"BDQ", "Bradford Forster Square"},
	{"BEA", "Bearley"},
	{"BEF", "Belford"},
	{"BEG", "Beighton"},
	{"BEL", "Belfast"},
	{"BEN", "Benson"},
	{"BES", "Bestwood Park"},
	{"BET", "Bethnal Green"},
	{"BEU", "Beulab"},
	{"BFD", "Bradford"},
	{"BFN", "Blaenrhondda"},
	{"BGN", "Brighton"},
	{"BGS", "Biggleswade"},
	{"BHD", "Belfast"},
	{"BHI", "Birmingham"},
	{"BHM", "Birmingham New Street"},
	{"BHO", "Birkdale"},
	{"BID", "Bidborough"},
	{"BIK", "Birkenhead"},
	{"BIL", "Bilbrook"},
	{"BIN", "Bingley"},
	{"BIO", "Birchington"},
	{"BIR", "Birmingham"},
	{"BIS", "Bishop Auckland"},
	{"BIT", "Bitterne"},
	{"BKG", "Barking"},
	{"BKJ", "Blackheath"},
	{"BKL", "Birkdale"},
	{"BKM", "Beckenham"},
	{"BKN", "Birkenhead North"},
	{"BKO", "Blackpool"},
	{"BLA", "Blackpool North"},
	{"BLB", "Blackpool South"},
	{"BLD", "Blackpool"},
	{"BLG", "Blaengarw"},
	{"BLK", "Blackpool"},
	{"BLL", "Blaengwrach"},
	{"BLN", "Balcombe"},
	{"BLO", "Bloxwich"},
	{"BLP", "Blackpool Pleasure Beach"},
	{"BLS", "Blairgowrie"},
	{"BLV", "Bellevue"},
	{"BMF", "Bamford"},
	{"BMG", "Bromsgrove"},
	{"BMH", "Bournemouth"},
	{"BML", "Bramley"},
	{"BMN", "Bramhall"},
	{"BMP", "Brampton"},
	{"BMS", "Birmingham Snow Hill"},
	{"BMT", "Barmouth"},
	{"BMY", "Bamber Bridge"},
	{"BNA", "Bangor (Wales)"},
	{"BNB", "Barnby Dun"},
	{"BNC", "Brancepeth"},
	{"BND", "Barnard Castle"},
	{"BNF", "Bonnyrigg"},
	{"BNG", "Brentford"},
	{"BNH", "Barnehurst"},
	{"BNI", "Burnham"},
	{"BNK", "Banknock"},
	{"BNL", "Bodnant Garden"},
	{"BNN", "Bangor"},
	{"BNO", "Brentford"},
	{"BNP", "Barnstaple"},
	{"BNR", "Barnehurst"},
	{"BNS", "Barnes"},
	{"BNT", "Brant Broughton"},
	{"BNU", "Burnham-on-Sea"},
	{"BNW", "Barnsley"},
	{"BOG", "Bogston"},
	{"BON", "Bonnybridge"},
	{"BOO", "Bootle"},
	{"BOR", "Bordon"},
	{"BOS", "Boston"},
	{"BOT", "Bottesford"},
	{"BOW", "Bow Brickhill"},
	{"BPW", "Bristol Parkway"},
	{"BRA", "Bradford"},
	{"BRC", "Brockenhurst"},
	{"BRE", "Brentwood"},
	{"BRF", "Bradford Forster Square"},
	{"BRG", "Bridlington"},
	{"BRI", "Bristol Temple Meads"},
	{"BRK", "Berwick-upon-Tweed"},
	{"BRL", "Brierley Hill"},
	{"BRM", "Brighouse"},
	{"BRN", "Brighton"},
	{"BRO", "Bromley"},
	{"BRP", "Bristol Parkway"},
	{"BRR", "Barrow-in-Furness"},
	{"BRS", "Bristol Temple Meads"},
	{"BRT", "Braintree"},
	{"BRU", "Bruton"},
	{"BRW", "Barrow-in-Furness"},
	{"BSB", "Basingstoke"},
	{"BSC", "Bishopstone"},
	{"BSD", "Blaenrhondda"},
	{"BSE", "Bury St Edmunds"},
	{"BSH", "Birstall"},
	{"BSK", "Basingstoke"},
	{"BSN", "Bishopstone"},
	{"BSO", "Bishops Stortford"},
	{"BSP", "Bishop's Stortford"},
	{"BSR", "Barassie"},
	{"BSS", "Bishops Stortford"},
	{"BST", "Bristol Temple Meads"},
	{"BTH", "Bath Spa"},
	{"BTN", "Brighton"},
	{"BTY", "Batley"},
	{"BUC", "Buckley"},
	{"BUG", "Burngullow"},
	{"BUI", "Builth Road"},
	{"BUK", "Buxted"},
	{"BUL", "Bullgill"},
	{"BUO", "Buxton"},
	{"BUR", "Burnley"},
	{"BUS", "Bury"},
	{"BUT", "Butlers Lane"},
	{"BUX", "Buxton"},
	{"BVA", "Blaenrhondda"},
	{"BWB", "Bridgwater"},
	{"BWD", "Blackwood"},
	{"BWK", "Berwick-upon-Tweed"},
	{"BWN", "Bow"},
	{"BXB", "Buxted"},
	{"BXD", "Bexleyheath"},
	{"BXH", "Bexhill"},
	{"BXW", "Bexley"},
	{"BXY", "Bexley"},
	{"BYD", "Barry Docks"},
	{"BYI", "Barrhill"},
	{"BYK", "Byker"},
	{"BYM", "Barry"},
	{"BYN", "Braystones"},
	{"CAD", "Cadoxton"},
	{"CAG", "Cark & Cartmel"},
	{"CAI", "Cairnryan"},
	{"CAL", "Calstock"},
	{"CAM", "Cambridge"},
	{"CAN", "Canonbury"},
	{"CAO", "Carnforth"},
	{"CAR", "Carlisle"},
	{"CAS", "Castleton (Greater Manchester)"},
	{"CAT", "Caterham"},
	{"CAU", "Causeway Bay"},
	{"CAV", "Caverswall"},
	{"CAY", "Caythorpe"},
	{"CBE", "Cambridge North"},
	{"CBG", "Cambridge"},
	{"CBN", "Cambridge North"},
	{"CBR", "Chester-le-Street"},
	{"CBS", "Corby"},
	{"CBW", "Cobham & Stoke d'Abernon"},
	{"CCH", "Chichester"},
	{"CCT", "Croft"},
	{"CDI", "Cardigan"},
	{"CDQ", "Cardiff Queen Street"},
	{"CDT", "Crediton"},
	{"CED", "Cheddington"},
	{"CEF", "Cliffe"},
	{"CEP", "Chepstow"},
	{"CFC", "Cliffe"},
	{"CFD", "Cardiff"},
	{"CFF", "Chafford Hundred"},
	{"CFN", "Caerphilly"},
	{"CFT", "Crofton Park"},
	{"CGW", "Coatbridge Sunnyside"},
	{"CHA", "Chatham"},
	{"CHC", "Cheltenham Spa"},
	{"CHD", "Cheshunt"},
	{"CHE", "Chelmsford"},
	{"CHF", "Chafford Hundred"},
	{"CHG", "Charing Cross"},
	{"CHH", "Cheadle Hulme"},
	{"CHI", "Chichester"},
	{"CHK", "Chislehurst"},
	{"CHL", "Chessington South"},
	{"CHM", "Chelmsford"},
	{"CHN", "Chessington North"},
	{"CHO", "Chorley"},
	{"CHP", "Chippenham"},
	{"CHR", "Chester"},
	{"CHS", "Cheshunt"},
	{"CHT", "Chatham"},
	{"CHW", "Chertsey"},
	{"CHX", "Charing Cross"},
	{"CIT", "City Thameslink"},
	{"CKL", "Chicklade"},
	{"CLJ", "Clapham Junction"},
	{"CLK", "Clarkston"},
	{"CLL", "Cellardyke"},
	{"CLN", "Clacton-on-Sea"},
	{"CLR", "Colchester"},
	{"CLS", "Cleethorpes"},
	{"CLT", "Cheltenham Spa"},
	{"CLU", "Clunderwen"},
	{"CLV", "Cleveleys"},
	{"CLW", "Colwall"},
	{"CMB", "Cambridge"},
	{"CMF", "Camforth"},
	{"CMN", "Camborne"},
	{"CMO", "Cambuslang"},
	{"CMR", "Carmarthen"},
	{"CMS", "Clacton-on-Sea"},
	{"CMT", "Cambuslang"},
	{"CNL", "Canal Street"},
	{"CNR", "Coatbridge"},
	{"CNW", "Canonbury"},
	{"COB", "Cobham"},
	{"COH", "Colehill"},
	{"COL", "Colchester"},
	{"CON", "Conon Bridge"},
	{"COO", "Cooden Beach"},
	{"COR", "Corsham"},
	{"COS", "Cosham"},
	{"COT", "Cotton"},
	{"COV", "Coventry"},
	{"COW", "Cowden"},
	{"CPH", "Coppermill Junction"},
	{"CPK", "Crystal Palace"},
	{"CPT", "Capenhurst"},
	{"CPW", "Carpenders Park"},
	{"CRA", "Cramlington"},
	{"CRB", "Crumlin"},
	{"CRD", "Cardiff Central"},
	{"CRE", "Crewe"},
	{"CRF", "Cardiff"},
	{"CRG", "Crowborough"},
	{"CRH", "Cranleigh"},
	{"CRI", "Criccieth"},
	{"CRK", "Cork"},
	{"CRL", "Carlisle"},
	{"CRM", "Cromer"},
	{"CRN", "Carnoustie"},
	{"CRO", "Croydon"},
	{"CRP", "Carpenders Park"},
	{"CRR", "Cromer"},
	{"CRS", "Crosskeys"},
	{"CRT", "Crewe"},
	{"CRU", "Crumlin"},
	{"CRW", "Crawley"},
	{"CRY", "Crystal Palace"},
	{"CSA", "Chessington South"},
	{"CSH", "Chessington"},
	{"CSN", "Caersws"},
	{"CSO", "Cosford"},
	{"CST", "Charing Cross"},
	{"CTK", "City Thameslink"},
	{"CTM", "Chatham"},
	{"CTN", "Cotton"},
	{"CTR", "Chester"},
	{"CTT", "Catterick Bridge"},
	{"CUF", "Culford"},
	{"CUH", "Culloden Moor"},
	{"CUM", "Cumberland"},
	{"CUW", "Cupar"},
	{"CWB", "Cwmbran"},
	{"CWL", "Cardiff"},
	{"CWM", "Cwmaman"},
	{"CWN", "Cwmfelin"},
	{"CYS", "Crystals"},
	{"DAL", "Dalmuir"},
	{"DAM", "Dalmally"},
	{"DAN", "Danescourt"},
	{"DAR", "Darlington"},
	{"DAS", "Dalmally"},
	{"DAT", "Dartmouth"},
	{"DBD", "Dalmarnock"},
	{"DBE", "Dalmeny"},
	{"DBI", "Derby"},
	{"DBL", "Dalmally"},
	{"DBR", "Dunbar"},
	{"DBS", "Derby"},
	{"DCG", "Dalcross"},
	{"DCT", "Doncaster"},
	{"DDG", "Dundee"},
	{"DDK", "Dundee"},
	{"DEA", "Deal"},
	{"DEB", "Debenham"},
	{"DEE", "Deeside"},
	{"DEM", "Dearham"},
	{"DEN", "Denby Dale"},
	{"DEP", "Deptford"},
	{"DER", "Derby"},
	{"DEW", "Dewsbury"},
	{"DFD", "Deptford"},
	{"DFR", "Dyffryn Ardudwy"},
	{"DGC", "Dunrobin Castle"},
	{"DGE", "Dorridge"},
	{"DGL", "Dalgleish"},
	{"DGN", "Dungeon"},
	{"DGY", "Dingwall"},
	{"DHM", "Durham"},
	{"DIG", "Digby & Sowton"},
	{"DKT", "Dunkeld & Birnam"},
	{"DLD", "Dolau"},
	{"DLE", "Dolgarrog"},
	{"DLG", "Dalmally"},
	{"DLH", "Dalehouse"},
	{"DLJ", "Dalston Junction"},
	{"DLK", "Dalkeith"},
	{"DLM", "Dalmuir"},
	{"DLN", "Darlington"},
	{"DLR", "Dollis Hill"},
	{"DLS", "Dalmeny"},
	{"DLT", "Dalton"},
	{"DLW", "Dalwhinnie"},
	{"DLY", "Dalry"},
	{"DMC", "Dalmeny"},
	{"DMF", "Dumfries"},
	{"DMK", "Drumchapel"},
	{"DML", "Drumchapel"},
	{"DMN", "Dalmeny"},
	{"DMP", "Drumpellier"},
	{"DMR", "Dalmarnock"},
	{"DMS", "Dalmeny"},
	{"DMY", "Dalmeny"},
	{"DNC", "Doncaster"},
	{"DNE", "Dunure"},
	{"DNF", "Dunfermline"},
	{"DNG", "Dingwall"},
	{"DNH", "Dinnington"},
	{"DNI", "Dalrymple"},
	{"DNK", "Dunblane"},
	{"DNL", "Dunloskie"},
	{"DNM", "Denmilne"},
	{"DNN", "Dingwall"},
	{"DNO", "Dunoon"},
	{"DNR", "Doncaster"},
	{"DNS", "Dunston"},
	{"DOC", "Dockyard"},
	{"DON", "Doncaster"},
	{"DOR", "Dorchester"},
	{"DOS", "Dorchester South"},
	{"DOW", "Dockyard"},
	{"DPD", "Deptford"},
	{"DRG", "Drayton Green"},
	{"DRM", "Drumry"},
	{"DRN", "Dronfield"},
	{"DRO", "Droitwich Spa"},
	{"DRU", "Drumchapel"},
	{"DRY", "Drumry"},
	{"DSL", "Dalston"},
	{"DST", "Dorchester"},
	{"DSY", "Daisyfield"},
	{"DTN", "Darton"},
	{"DUD", "Duddeston"},
	{"DUF", "Dufftown"},
	{"DUG", "Dunblane"},
	{"DUI", "Duirinish"},
	{"DUK", "Dunkeld"},
	{"DUL", "Dulwich"},
	{"DUM", "Dumfries"},
	{"DUN", "Dunbar"},
	{"DUO", "Dunoon"},
	{"DUR", "Durham"},
	{"DVN", "Devonport"},
	{"DVP", "Devonport"},
	{"DWD", "Dowlais"},
	{"DWL", "Dalwhinnie"},
	{"DWN", "Downham Market"},
	{"EAL", "Ealing Broadway"},
	{"EBN", "East Boldon"},
	{"EBR", "East Brixton"},
	{"EBT", "Ebbsfleet International"},
	{"ECC", "Eccles"},
	{"ECO", "East Coast"},
	{"ECR", "East Croydon"},
	{"ECS", "Eccles"},
	{"EDB", "Edinburgh"},
	{"EDG", "Edgware Road"},
	{"EDI", "Edinburgh Waverley"},
	{"EDL", "Edinburgh"},
	{"EDN", "Edinburgh"},
	{"EDR", "Edenbridge"},
	{"EDS", "Edstone"},
	{"EDW", "Edgware Road"},
	{"EFF", "Effingham Junction"},
	{"EGR", "Egton"},
	{"EGT", "Eggington Junction"},
	{"EGY", "Egremont"},
	{"EKL", "East Kilbride"},
	{"ELD", "Elderslie"},
	{"ELG", "Elgin"},
	{"ELN", "Elgin"},
	{"ELR", "Elsecar"},
	{"ELS", "Elsenham"},
	{"ELT", "Eltham"},
	{"ELY", "Ely"},
	{"EMD", "East Midlands Parkway"},
	{"EMP", "East Midlands Parkway"},
	{"EMS", "Emsworth"},
	{"ENG", "Enfield"},
	{"ENT", "Entwistle"},
	{"EPD", "Epping"},
	{"EPS", "Epsom"},
	{"ERD", "Erdington"},
	{"ESH", "Esher"},
	{"EST", "Eastbourne"},
	{"ETL", "Ethelburga"},
	{"EUS", "London Euston"},
	{"EVE", "Evesham"},
	{"EVN", "Everton"},
	{"EWD", "Eastwood"},
	{"EWE", "Ewe"},
	{"EWR", "East Worthing"},
	{"EXC", "Exeter Central"},
	{"EXD", "Exeter St Davids"},
	{"EXM", "Exmouth"},
	{"EXN", "Exeter Central"},
	{"EXS", "Exeter St Thomas"},
	{"EXT", "Exeter St Davids"},
	{"FAL", "Falmouth"},
	{"FAV", "Faversham"},
	{"FAZ", "Fazakerley"},
	{"FBY", "Ferriby"},
	{"FCN", "Falconwood"},
	{"FEL", "Feltham"},
	{"FEN", "Feniton"},
	{"FER", "Ferme Park"},
	{"FGH", "Fenchurch Street"},
	{"FGW", "Fishguard"},
	{"FIT", "Fitzwilliam"},
	{"FKC", "Folkestone Central"},
	{"FKK", "Folkestone"},
	{"FKW", "Folkestone West"},
	{"FLD", "Fieldhead"},
	{"FLI", "Flint"},
	{"FLM", "Flimby"},
	{"FLN", "Flint"},
	{"FLT", "Fleet"},
	{"FMT", "Formby"},
	{"FNB", "Finsbury Park"},
	{"FNC", "Fenchurch Street"},
	{"FNR", "Farnborough"},
	{"FNT", "Frant"},
	{"FOC", "Folkestone"},
	{"FOD", "Ford"},
	{"FOK", "Folkestone"},
	{"FOR", "Formby"},
	{"FPK", "Finsbury Park"},
	{"FRM", "Fareham"},
	{"FRN", "Farnborough North"},
	{"FRO", "Frodsham"},
	{"FRW", "Freshwater"},
	{"FSB", "Fishersgate"},
	{"FSG", "Fishguard & Goodwick"},
	{"FSS", "Farnworth"},
	{"FTM", "Farnham"},
	{"FWY", "Fishguard"},
	{"FZH", "Fazakerley"},
	{"GAR", "Garforth"},
	{"GAT", "Gatwick Airport"},
	{"GBD", "Gobowen"},
	{"GBK", "Glenbuck"},
	{"GBL", "Greenbank"},
	{"GCH", "Grange-over-Sands"},
	{"GCR", "Gloucester"},
	{"GCT", "Glasgow Central"},
	{"GCV", "Glencarron Platform"},
	{"GEA", "Glenealmond"},
	{"GFN", "Griffithstown"},
	{"GFO", "Glasshoughton"},
	{"GGV", "Giggleswick"},
	{"GHD", "Gateshead"},
	{"GIL", "Gilshochill"},
	{"GIP", "Gipsy Hill"},
	{"GKC", "Gatwick Airport"},
	{"GLA", "Glasgow"},
	{"GLC", "Glasgow Central"},
	{"GLM", "Glenwhilly"},
	{"GLO", "Gloucester"},
	{"GLP", "Gilshochill"},
	{"GLS", "Glasshoughton"},
	{"GLT", "Galloway"},
	{"GLY", "Glenluce"},
	{"GNB", "Grangemouth"},
	{"GNH", "Greenhithe"},
	{"GNL", "Greenhill"},
	{"GNM", "Grantown-on-Spey"},
	{"GNT", "Grantham"},
	{"GNW", "Greenwich"},
	{"GOS", "Gosport"},
	{"GPK", "Grange Park"},
	{"GPO", "Grange Park"},
	{"GRA", "Grays"},
	{"GRB", "Grimsby"},
	{"GRC", "Grays"},
	{"GRF", "Grantham"},
	{"GRK", "Greenock"},
	{"GRL", "Greenock"},
	{"GRM", "Grimsby"},
	{"GRN", "Grange-over-Sands"},
	{"GRO", "Grimsby"},
	{"GRS", "Grimsby"},
	{"GRT", "Grantham"},
	{"GRV", "Grove Park"},
	{"GRY", "Grays"},
	{"GSD", "Garsdale"},
	{"GSN", "Gainsborough"},
	{"GST", "Guiseley"},
	{"GTW", "Gatwick Airport"},
	{"GUI", "Guildford"},
	{"GUL", "Gunnislake"},
	{"GUN", "Gunnislake"},
	{"GVE", "Gravesend"},
	{"GWE", "Great Western"},
	{"GWN", "Gowerton"},
	{"GYM", "Gympie"},
	{"HAB", "Habrough"},
	{"HAC", "Hatch End"},
	{"HAD", "Hadfield"},
	{"HAG", "Hagley"},
	{"HAH", "Halesworth"},
	{"HAJ", "Harlington"},
	{"HAL", "Halifax"},
	{"HAM", "Hammersmith"},
	{"HAN", "Hanborough"},
	{"HAP", "Harpenden"},
	{"HAR", "Harrogate"},
	{"HAS", "Hastings"},
	{"HAT", "Hatfield"},
	{"HAV", "Havant"},
	{"HAW", "Hawarden"},
	{"HBD", "Hebden Bridge"},
	{"HBN", "Hebburn"},
	{"HBY", "Humberside"},
	{"HCB", "Hockliffe"},
	{"HCH", "Hitchin"},
	{"HDB", "Headingley"},
	{"HDG", "Headingley"},
	{"HDL", "Headingley"},
	{"HDM", "Haddenham & Thame Parkway"},
	{"HDN", "Hebden Bridge"},
	{"HDW", "Haddenham"},
	{"HEC", "Heckington"},
	{"HEI", "Hest Bank"},
	{"HEL", "Helensburgh"},
	{"HEO", "Heol Senni"},
	{"HER", "Hertford"},
	{"HES", "Heswall"},
	{"HEV", "Hever"},
	{"HEW", "Herne Bay"},
	{"HFD", "Hereford"},
	{"HFN", "Halfpenny Green"},
	{"HGD", "Hagley"},
	{"HGM", "Higham"},
	{"HGN", "High Wycombe"},
	{"HGS", "Highbury & Islington"},
	{"HGT", "Highgate"},
	{"HGY", "Highgate"},
	{"HHB", "Horley"},
	{"HHD", "Hertford"},
	{"HHL", "Highfields"},
	{"HHN", "Hildenborough"},
	{"HHY", "Highbury"},
	{"HIG", "Higham"},
	{"HIT", "Hitchin"},
	{"HLD", "Holderness"},
	{"HLG", "Hillington"},
	{"HLN", "Hellifield"},
	{"HLR", "Halewood"},
	{"HLW", "Helow"},
	{"HMC", "Hammersmith"},
	{"HML", "Hammerton"},
	{"HMN", "Hammersmith"},
	{"HMP", "Hamp"},
	{"HMT", "Hemel Hempstead"},
	{"HNA", "Herne Bay"},
	{"HNB", "Honeybourne"},
	{"HNC", "Henley-in-Arden"},
	{"HND", "Hindley"},
	{"HNH", "Herne Hill"},
	{"HNK", "Henwick"},
	{"HNL", "Hanwell"},
	{"HNT", "Hintlesham"},
	{"HNX", "Hendon"},
	{"HNY", "Hornsey"},
	{"HOC", "Hockley"},
	{"HOK", "Hook"},
	{"HOL", "Hollingbourne"},
	{"HOM", "Homerton"},
	{"HON", "Honesty"},
	{"HOO", "Hoo Junction"},
	{"HOR", "Horley"},
	{"HOS", "Hoscar"},
	{"HOT", "Hotham"},
	{"HOV", "Hove"},
	{"HOW", "Howden"},
	{"HPD", "Harpenden"},
	{"HPE", "Hammersmith"},
	{"HPK", "Harlesden"},
	{"HPS", "Harpenden"},
	{"HRD", "Hereford"},
	{"HRH", "Harwich"},
	{"HRL", "Harlesden"},
	{"HRM", "Horsmonden"},
	{"HRN", "Harringay"},
	{"HRO", "Harrow"},
	{"HRP", "Hartlepool"},
	{"HRR", "Harrow & Wealdstone"},
	{"HRS", "Horsham"},
	{"HRT", "Hertford North"},
	{"HRW", "Harrow-on-the-Hill"},
	{"HRY", "Horley"},
	{"HSB", "Hessle"},
	{"HSD", "Hessle"},
	{"HSK", "Hassocks"},
	{"HSL", "Hassocks"},
	{"HSP", "Harrow-on-the-Hill"},
	{"HST", "Hastings"},
	{"HSW", "Haswell"},
	{"HTE", "Hattersley"},
	{"HTF", "Hatfield"},
	{"HTN", "Hartington"},
	{"HTO", "Hatton"},
	{"HTP", "Hartlepool"},
	{"HTW", "Headstone Lane"},
	{"HUC", "Hucknall"},
	{"HUD", "Huddersfield"},
	{"HUL", "Hull"},
	{"HUN", "Huntingdon"},
	{"HUO", "Hunstanton"},
	{"HUR", "Hursley"},
	{"HUT", "Hutton Cranswick"},
	{"HWB", "Hawarden Bridge"},
	{"HWC", "Howwood"},
	{"HWD", "Horwich Parkway"},
	{"HWN", "Heworth"},
	{"HWV", "Horwich Parkway"},
	{"HWW", "Hatherleigh"},
	{"HXX", "Heathrow"},
	{"HYC", "Hythe (Kent)"},
	{"HYD", "Heywood"},
	{"HYK", "Hykeham"},
	{"HYL", "Hylton"},
	{"HYM", "Haymarket"},
	{"HYN", "Heyford"},
	{"HYR", "Haydock"},
	{"HYS", "Heyshaw"},
	{"HYW", "Heywood"},
	{"IFD", "Ipswich"},
	{"IFT", "Ifield"},
	{"IGD", "Ingoldisthorpe"},
	{"ILK", "Ilkeston"},
	{"ILY", "Ilkley"},
	{"INV", "Inverness"},
	{"IPS", "Ipswich"},
	{"IRL", "Irlam"},
	{"IRV", "Irvine"},
	{"ISL", "Islip"},
	{"IVR", "Inverness"},
	{"KBW", "Kibworth"},
	{"KDY", "Kirkcaldy"},
	{"KEM", "Kempton Park"},
	{"KEN", "Kensington"},
	{"KGL", "Kegworth"},
	{"KGP", "Kings Langley"},
	{"KGS", "Kingston"},
	{"KGT", "Kingston"},
	{"KGX", "London Kings Cross"},
	{"KID", "Kidderminster"},
	{"KIL", "Kilmarnock"},
	{"KIN", "Kings Nympton"},
	{"KIR", "Kirkham & Wesham"},
	{"KIT", "Kirtlebridge"},
	{"KLN", "Kilwinning"},
	{"KLY", "Keighley"},
	{"KMS", "Kidsgrove"},
	{"KNA", "Knaresborough"},
	{"KNE", "Knebworth"},
	{"KNF", "Kings Norton"},
	{"KNG", "Kingston"},
	{"KNI", "Knighton"},
	{"KNL", "Knolton"},
	{"KNN", "Kennington"},
	{"KNR", "Knucklas"},
	{"KNS", "Kennishead"},
	{"KNT", "Knutsford"},
	{"KNW", "Kenilworth"},
	{"KPA", "Kirknewton"},
	{"KPT", "Kempston Hardwick"},
	{"KRK", "Kirkby"},
	{"KSN", "Kirksanton"},
	{"KSS", "Kirkby Stephen"},
	{"KTH", "Kentish Town"},
	{"KTK", "Kentish Town"},
	{"KTN", "Kentish Town"},
	{"KTW", "Kettering"},
	{"KWB", "Knowbury"},
	{"KWG", "Kewstoke"},
	{"KWN", "Kilwinning"},
	{"KYL", "Kyle of Lochalsh"},
	{"LAC", "Lancing"},
	{"LAK", "Lakenheath"},
	{"LAM", "Lamphey"},
	{"LAN", "Lancaster"},
	{"LAR", "Largs"},
	{"LBC", "London Bridge"},
	{"LBG", "London Bridge"},
	{"LBR", "Llandre"},
	{"LBZ", "Llanbrynmair"},
	{"LCC", "Leicester"},
	{"LCD", "Leeds"},
	{"LCN", "Lichfield City"},
	{"LCS", "Lincoln Central"},
	{"LCW", "Llanbadarn"},
	{"LDB", "Llandaff"},
	{"LDN", "London"},
	{"LDS", "Leeds"},
	{"LEB", "Leigh-on-Sea"},
	{"LEI", "Leicester"},
	{"LEM", "Leamington Spa"},
	{"LEN", "Lenham"},
	{"LEO", "Leominster"},
	{"LES", "Letchworth Garden City"},
	{"LEU", "Leuchars"},
	{"LEW", "Lewes"},
	{"LFD", "Lichfield"},
	{"LFT", "Loftus"},
	{"LGN", "Loughton"},
	{"LGO", "Langho"},
	{"LGS", "Loughborough"},
	{"LGW", "Gatwick Airport"},
	{"LHA", "Liverpool Lime Street"},
	{"LHD", "Leatherhead"},
	{"LHE", "Leatherhead"},
	{"LHG", "Laughton"},
	{"LHN", "Llandrindod"},
	{"LIC", "Lichfield City"},
	{"LIN", "Lincoln"},
	{"LIV", "Liverpool Lime Street"},
	{"LKE", "Lake"},
	{"LKW", "Lakeside"},
	{"LLC", "Llanrwst"},
	{"LLD", "Llandudno"},
	{"LLE", "Llandudno"},
	{"LLF", "Llanfairfechan"},
	{"LLG", "Llangefni"},
	{"LLH", "Llanharan"},
	{"LLI", "Llandybie"},
	{"LLL", "Llanelli"},
	{"LLN", "Llandrindod Wells"},
	{"LLO", "Llandovery"},
	{"LLS", "Llansamlet"},
	{"LLT", "Llantwit Major"},
	{"LLV", "Llanwrda"},
	{"LLW", "Llandybie"},
	{"LLY", "Llandybie"},
	{"LMS", "Lymstone"},
	{"LMT", "Lymington Town"},
	{"LMY", "Lymington Pier"},
	{"LNC", "Lancaster"},
	{"LNE", "Lincoln"},
	{"LNR", "Llandrindod Wells"},
	{"LNS", "Llansamlet"},
	{"LNW", "Llanwrtyd Wells"},
	{"LOB", "London Blackfriars"},
	{"LOC", "Loch"},
	{"LOF", "Lofthouse"},
	{"LOO", "Looe"},
	{"LOS", "Lostwithiel"},
	{"LOW", "Lowestoft"},
	{"LPG", "Liverpool Central"},
	{"LPL", "Liverpool"},
	{"LPT", "Liverpool Street"},
	{"LPW", "Liverpool Central"},
	{"LRB", "Larbert"},
	{"LRC", "Largs"},
	{"LRD", "Lairg"},
	{"LRG", "Largs"},
	{"LSP", "Liverpool South Parkway"},
	{"LST", "Liverpool Street"},
	{"LTM", "Littlehampton"},
	{"LTN", "Luton"},
	{"LTP", "Luton Airport Parkway"},
	{"LTS", "Leigh-on-Sea"},
	{"LTV", "Llantrisant"},
	{"LUD", "Luddenden Foot"},
	{"LUT", "Luton"},
	{"LVC", "Llandrindod Wells"},
	{"LVJ", "Liverpool Lime Street"},
	{"LVL", "Liverpool Lime Street"},
	{"LVN", "Livingston North"},
	{"LVS", "Livingston South"},
	{"LWH", "Lowestoft"},
	{"LWR", "Lowther"},
	{"LWT", "Lewisham"},
	{"LYC", "Lychgate"},
	{"LYD", "Lydney"},
	{"LYE", "Lye"},
	{"LYM", "Lymington"},
	{"LYP", "Lydney"},
	{"MAN", "Manchester Piccadilly"},
	{"MAO", "Manchester Airport"},
	{"MAR", "Margate"},
	{"MAS", "Mansfield"},
	{"MAT", "Matlock"},
	{"MBR", "Middlesbrough"},
	{"MCB", "Machynlleth"},
	{"MCC", "Manchester"},
	{"MCO", "Macclesfield"},
	{"MCV", "Macclesfield"},
	{"MDB", "Middlesbrough"},
	{"MDS", "Meadowhall"},
	{"MDV", "Meadowhall"},
	{"MDW", "Meadowhall"},
	{"MEL", "Meldon"},
	{"MEN", "Menheniot"},
	{"MER", "Merthyr Tydfil"},
	{"MES", "Merstham"},
	{"MFA", "Manchester"},
	{"MFT", "Mansfield"},
	{"MGN", "Margam"},
	{"MHM", "Marsham"},
	{"MID", "Middlesbrough"},
	{"MIJ", "Mirfield"},
	{"MIK", "Milnrow"},
	{"MIL", "Millbrook"},
	{"MIM", "Mirfield"},
	{"MIS", "Milsington"},
	{"MKC", "Milton Keynes Central"},
	{"MKE", "Market Harborough"},
	{"MKN", "Milton Keynes Central"},
	{"MLG", "Mallaig"},
	{"MLL", "Millfield"},
	{"MLN", "Malton"},
	{"MLP", "Mallaig"},
	{"MLR", "Millerhill"},
	{"MLS", "Mallaig"},
	{"MLT", "Malt"},
	{"MLW", "Mallaig"},
	{"MMO", "Moor Street"},
	{"MNC", "Manchester"},
	{"MNE", "Maryport"},
	{"MNR", "Manningtree"},
	{"MOB", "Mobberley"},
	{"MOG", "Morecambe"},
	{"MOR", "Morecambe"},
	{"MOS", "Mossley"},
	{"MOT", "Mottram"},
	{"MPT", "Maesteg Parkway"},
	{"MRB", "Marylebone"},
	{"MRC", "Margate"},
	{"MRF", "Mirfield"},
	{"MRN", "Morden South"},
	{"MRP", "Marple"},
	{"MRS", "Morpeth"},
	{"MRT", "Mortimer"},
	{"MRV", "Morley"},
	{"MRY", "Marylebone"},
	{"MSB", "Mossley"},
	{"MSN", "Maesteg"},
	{"MSP", "Morpeth"},
	{"MSR", "Mossley"},
	{"MST", "Mossley"},
	{"MSW", "Mossworth"},
	{"MTA", "Maesteg"},
	{"MTH", "Merthyr Vale"},
	{"MTL", "Matlock"},
	{"MTM", "Mottingham"},
	{"MTN", "Motherwell"},
	{"MTO", "Mytholmroyd"},
	{"MTP", "Matlock"},
	{"MTR", "Motherwell"},
	{"MTS", "Merthyr Tydfil"},
	{"MTW", "Matlock Bath"},
	{"MUB", "Muswell Hill"},
	{"MUF", "Mudford"},
	{"MUI", "Muir of Ord"},
	{"MUO", "Muirhouse"},
	{"NCS", "Newcastle"},
	{"NDL", "Nailsea & Backwell"},
	{"NEI", "Neilston"},
	{"NEL", "Neilston"},
	{"NEM", "New Eltham"},
	{"NEP", "Nepean"},
	{"NES", "Neath"},
	{"NET", "Netherfield"},
	{"NEW", "Newcastle"},
	{"NFD", "Northfield"},
	{"NGA", "Norgate"},
	{"NGT", "Nottingham"},
	{"NHE", "Netherhope"},
	{"NIT", "Nitshill"},
	{"NKB", "Normanton"},
	{"NKN", "Normanby"},
	{"NLN", "North Llanrwst"},
	{"NLT", "Nottingham"},
	{"NMC", "Normanton"},
	{"NML", "New Mills Central"},
	{"NMN", "New Mills Newtown"},
	{"NMP", "Northampton"},
	{"NMS", "Norwood"},
	{"NMT", "Normanton"},
	{"NNB", "Nunthorpe"},
	{"NNP", "Northampton"},
	{"NOR", "Norwich"},
	{"NOT", "Nottingham"},
	{"NRB", "Narberth"},
	{"NRN", "Narborough"},
	{"NRT", "Norwich"},
	{"NRW", "Norwich"},
	{"NSB", "Neasden"},
	{"NSG", "Norwood"},
	{"NSL", "Naseby"},
	{"NSN", "Neston"},
	{"NTH", "Northampton"},
	{"NTN", "Northallerton"},
	{"NTP", "Northampton"},
	{"NTR", "Nunthorpe"},
	{"NUN", "Nuneaton"},
	{"NVN", "Nuneaton"},
	{"NWB", "Newbury"},
	{"NWD", "Norwood Junction"},
	{"NWE", "New Eltham"},
	{"NWN", "Newtown"},
	{"NWP", "Newport"},
	{"NWR", "New Barnet"},
	{"NWT", "Newtonmore"},
	{"NXG", "Nexus Grasmere"},
	{"OAK", "Oakham"},
	{"OBN", "Oban"},
	{"ODD", "Oddington"},
	{"OKH", "Oakham"},
	{"OKL", "Oak Leaf"},
	{"OKN", "Okehampton"},
	{"OLF", "Oldfield Park"},
	{"OLD", "Oldham"},
	{"OLT", "Oldfield Park"},
	{"OMS", "Ormskirk"},
	{"ORE", "Ore"},
	{"ORM", "Ormskirk"},
	{"ORP", "Orpington"},
	{"ORR", "Orrell"},
	{"OVR", "Overton"},
	{"OXD", "Oxford"},
	{"OXF", "Oxford"},
	{"OXS", "Oxford Parkway"},
	{"PAD", "London Paddington"},
	{"PAG", "Paignton"},
	{"PAL", "Palmers Green"},
	{"PAN", "Pannal"},
	{"PAR", "Par"},
	{"PAT", "Patricroft"},
	{"PBL", "Parbold"},
	{"PBO", "Peterborough"},
	{"PCN", "Peckham Rye"},
	{"PCT", "Peckham"},
	{"PDE", "Paddock Wood"},
	{"PDG", "Padding"},
	{"PDW", "Paddock Wood"},
	{"PEA", "Penarth"},
	{"PEG", "Penge East"},
	{"PEN", "Penrith"},
	{"PER", "Perth"},
	{"PES", "Penge East"},
	{"PET", "Peterborough"},
	{"PEW", "Pewsey"},
	{"PEY", "Penley"},
	{"PGN", "Paignton"},
	{"PHG", "Patchway"},
	{"PHL", "Philadelphia"},
	{"PHR", "Pinhoe"},
	{"PHS", "Peterborough"},
	{"PIT", "Pitlochry"},
	{"PKG", "Peckham Rye"},
	{"PKS", "Peckham"},
	{"PKW", "Parkway"},
	{"PLM", "Plymouth"},
	{"PLU", "Plumstead"},
	{"PLW", "Plumstead"},
	{"PLY", "Plymouth"},
	{"PMB", "Pemberton"},
	{"PMD", "Pembroke Dock"},
	{"PME", "Portsmouth"},
	{"PMH", "Portsmouth Harbour"},
	{"PMK", "Plumstead"},
	{"PML", "Pemberton"},
	{"PMN", "Pemberton"},
	{"PMR", "Peterborough"},
	{"PMS", "Pemberton"},
	{"PMW", "Portsmouth & Southsea"},
	{"PNA", "Penmaenmawr"},
	{"PNL", "Pontlottyn"},
	{"PNN", "Pontardawe"},
	{"PNR", "Pinhoe"},
	{"PNT", "Pentre"},
	{"PNY", "Pontypridd"},
	{"POK", "Polkemmet"},
	{"POL", "Polegate"},
	{"POM", "Poole"},
	{"PON", "Pontefract"},
	{"POO", "Poole"},
	{"POP", "Poplar"},
	{"POR", "Portsmouth"},
	{"POS", "Portsmouth & Southsea"},
	{"POT", "Potters Bar"},
	{"POW", "Pewsey"},
	{"PPL", "Poppleton"},
	{"PRE", "Preston"},
	{"PRH", "Porthmadog"},
	{"PRI", "Prestwick International"},
	{"PRN", "Perranporth"},
	{"PRR", "Prudhoe"},
	{"PRS", "Princes Risborough"},
	{"PRT", "Perth"},
	{"PRU", "Prudhoe"},
	{"PRW", "Prestwick"},
	{"PSC", "Peterborough"},
	{"PSH", "Portishead"},
	{"PSL", "Pegswood"},
	{"PSN", "Pulborough"},
	{"PTD", "Pontardulais"},
	{"PTG", "Pontrilas"},
	{"PTK", "Pontypool & New Inn"},
	{"PTL", "Pontllanfraith"},
	{"PTM", "Peterham"},
	{"PTN", "Pertenhall"},
	{"PTO", "Portishead"},
	{"PTR", "Pontrhydyfen"},
	{"PTS", "Portsmouth"},
	{"PTT", "Petts Wood"},
	{"PUL", "Pulborough"},
	{"PUR", "Purley"},
	{"PUT", "Putney"},
	{"PWE", "Pwllheli"},
	{"PWL", "Pwllheli"},
	{"PWY", "Pewsey"},
	{"PYC", "Pyle"},
	{"PYE", "Pye Corner"},
	{"PYG", "Pyle"},
	{"PYL", "Pyle"},
	{"QBR", "Queens Road (Peckham)"},
	{"QRP", "Queens Road (Peckham)"},
	{"QUI", "Quintrell Downs"},
	{"RAI", "Rainford"},
	{"RAM", "Ramsgate"},
	{"RAN", "Rainhill"},
	{"RAY", "Raynes Park"},
	{"RBR", "Redbridge"},
	{"RCC", "Rochdale"},
	{"RCD", "Rochdale"},
	{"RCH", "Rochdale"},
	{"RDB", "Redbridge"},
	{"RDD", "Redditch"},
	{"RDG", "Reading"},
	{"RDN", "Reading"},
	{"RDR", "Reddish North"},
	{"RDS", "Reddish South"},
	{"RDT", "Redcar Central"},
	{"RDW", "Redditch"},
	{"REA", "Reading"},
	{"REC", "Reckitt"},
	{"RED", "Redhill"},
	{"REI", "Reigate"},
	{"REN", "Renfrew"},
	{"RGT", "Reigate"},
	{"RGW", "Ringwood"},
	{"RHL", "Redhill"},
	{"RHO", "Rhosneigr"},
	{"RHY", "Rhymney"},
	{"RIL", "Rillaton"},
	{"RKT", "Rickmansworth"},
	{"RLG", "Rolleston-on-Dove"},
	{"ROB", "Robertsbridge"},
	{"ROC", "Roch"},
	{"ROG", "Ropley"},
	{"ROL", "Rolleston"},
	{"ROM", "Romford"},
	{"RON", "Roose"},
	{"ROS", "Ross-on-Wye"},
	{"ROT", "Rotherham"},
	{"ROU", "Roughton Road"},
	{"ROW", "Rowlands Castle"},
	{"RPY", "Ramsgate"},
	{"RRB", "Redcar"},
	{"RSY", "Rosyth"},
	{"RTN", "Retford"},
	{"RUA", "Ruabon"},
	{"RUG", "Rugby"},
	{"RUH", "Rugeley"},
	{"RUN", "Runcorn"},
	{"RUT", "Ruthin"},
	{"RVB", "Ravensthorpe"},
	{"RWC", "Rowlands Castle"},
	{"SAA", "Saint Annes-on-the-Sea"},
	{"SAL", "Salford"},
	{"SAM", "Saltmarshe"},
	{"SAN", "Sandwell & Dudley"},
	{"SAP", "Saffron Walden"},
	{"SAR", "Sarn"},
	{"SAT", "Saltaire"},
	{"SAV", "Savenake"},
	{"SAW", "Sawbridgeworth"},
	{"SBR", "Sandhurst"},
	{"SBS", "Sebastopol"},
	{"SBT", "Saltburn"},
	{"SCB", "Scarborough"},
	{"SCG", "Scunthorpe"},
	{"SCO", "Scone"},
	{"SCR", "Scarborough"},
	{"SCT", "Scotscalder"},
	{"SCU", "Scunthorpe"},
	{"SDC", "Sunderland"},
	{"SDG", "Sandling"},
	{"SDL", "Stroud"},
	{"SDN", "Swindon"},
	{"SDR", "Sanderstead"},
	{"SDW", "Sandown"},
	{"SEA", "Seaham"},
	{"SEB", "Selby"},
	{"SEC", "Selhurst"},
	{"SEF", "Seaford"},
	{"SEG", "Selly Oak"},
	{"SEH", "Seaham"},
	{"SEL", "Selby"},
	{"SEN", "Shenfield"},
	{"SEO", "Seven Oaks"},
	{"SEV", "Sevenoaks"},
	{"SFA", "Shaftesbury"},
	{"SFD", "Stafford"},
	{"SFN", "Saffron Walden"},
	{"SFO", "Salford"},
	{"SFQ", "Stafford"},
	{"SFR", "Salford Crescent"},
	{"SFS", "Silverstone"},
	{"SFY", "Saffron Walden"},
	{"SGM", "Snaresbrook"},
	{"SHB", "Shoeburyness"},
	{"SHD", "Shieldmuir"},
	{"SHE", "Sheffield"},
	{"SHF", "Sheffield"},
	{"SHG", "Shillingstone"},
	{"SHH", "Shoeburyness"},
	{"SHI", "Shields Road"},
	{"SHJ", "Shenfield"},
	{"SHL", "Shalford"},
	{"SHM", "Shoreham-by-Sea"},
	{"SHN", "Shenton"},
	{"SHO", "Shoreham-by-Sea"},
	{"SHP", "Shepperton"},
	{"SHR", "Shrewsbury"},
	{"SHS", "Shoreham-by-Sea"},
	{"SHT", "Shrewsbury"},
	{"SHU", "Shudehill"},
	{"SHV", "Shillingstone"},
	{"SHW", "Shrewsbury"},
	{"SHY", "Selly Oak"},
	{"SIG", "Sighthill"},
	{"SIL", "Sileby"},
	{"SIN", "Sinfin"},
	{"SIT", "Sittingbourne"},
	{"SIV", "Silver Street"},
	{"SJP", "St James Park"},
	{"SKE", "Skegness"},
	{"SKG", "Skewen"},
	{"SKI", "Skipton"},
	{"SKN", "Skegness"},
	{"SKP", "Skipton"},
	{"SKT", "Skewen"},
	{"SKW", "Skegness"},
	{"SLA", "Slateford"},
	{"SLO", "Slough"},
	{"SLS", "Slateford"},
	{"SLT", "Saltaire"},
	{"SLW", "Slough"},
	{"SLY", "Saltley"},
	{"SMB", "Stamford"},
	{"SMC", "Smallbrook Junction"},
	{"SMD", "Smedley"},
	{"SMG", "Steaming"},
	{"SMK", "Smethwick"},
	{"SML", "Smallbrook"},
	{"SMN", "Stamford"},
	{"SMO", "Smethwick"},
	{"SMR", "St Mary's"},
	{"SMS", "Smethwick"},
	{"SMT", "Smethwick Rolfe Street"},
	{"SMW", "Smethwick"},
	{"SNF", "Snaresbrook"},
	{"SNH", "Shenfield"},
	{"SNK", "Snodland"},
	{"SNO", "Snaresbrook"},
	{"SNS", "Snaresbrook"},
	{"SOA", "Southampton Airport Parkway"},
	{"SOB", "Sole Street"},
	{"SOC", "Stockport"},
	{"SOG", "Sough"},
	{"SOL", "Solihull"},
	{"SOM", "Somerton"},
	{"SON", "Sonning"},
	{"SOP", "Southport"},
	{"SOR", "Sorbie"},
	{"SOU", "Southampton Central"},
	{"SOW", "Sowton"},
	{"SOY", "Solihull"},
	{"SPB", "Spondon"},
	{"SPF", "Spital"},
	{"SPN", "Spondon"},
	{"SPO", "Spondon"},
	{"SPS", "St Pancras International"},
	{"SQE", "Squires Gate"},
	{"SRA", "Strathcarron"},
	{"SRB", "Stirling"},
	{"SRC", "Strathcarron"},
	{"SRD", "Stroud"},
	{"SRG", "Shortlands"},
	{"SRK", "Stoke Newington"},
	{"SRL", "Shortlands"},
	{"SRM", "Strathmore"},
	{"SRN", "Sheringham"},
	{"SRO", "Stranraer"},
	{"SRP", "Stirling"},
	{"SRR", "Sheringham"},
	{"SRS", "Stourbridge"},
	{"SRT", "Strathaven"},
	{"SRU", "Stroud"},
	{"SRV", "Strawberry Hill"},
	{"SRW", "Strathcarron"},
	{"SSC", "Stourbridge"},
	{"SSE", "Sole Street"},
	{"SSG", "Snaresbrook"},
	{"SSH", "Stourbridge"},
	{"SSM", "Stourbridge"},
	{"SSN", "Stourbridge"},
	{"SSO", "Strood"},
	{"SSP", "Stourbridge"},
	{"SSS", "Stourbridge"},
	{"SST", "Stourbridge"},
	{"SSW", "Slough"},
	{"STA", "Staveley"},
	{"STB", "Stirling"},
	{"STC", "Stockport"},
	{"STD", "Strood"},
	{"STE", "Stetchford"},
	{"STF", "Stafford"},
	{"STG", "Stoke-on-Trent"},
	{"STH", "Streatham"},
	{"STI", "Stirling"},
	{"STJ", "St Johns"},
	{"STK", "Stoke-on-Trent"},
	{"STL", "Stowmarket"},
	{"STM", "Streatham"},
	{"STN", "Staines"},
	{"STO", "Stoke-on-Trent"},
	{"STP", "St Pancras International"},
	{"STR", "Stow"},
	{"STS", "St Andrews"},
	{"STT", "Streatham"},
	{"STU", "Streatham"},
	{"STV", "Stevenage"},
	{"STW", "Stowmarket"},
	{"STY", "Stoneythorpe"},
	{"SUA", "Surbiton"},
	{"SUC", "Sunderland"},
	{"SUL", "Sully"},
	{"SUN", "Sunderland"},
	{"SUO", "Surbiton"},
	{"SUR", "Surbiton"},
	{"SUY", "Sully"},
	{"SVH", "Shoreham (Kent)"},
	{"SVM", "Staveley"},
	{"SVN", "Seven Sisters"},
	{"SVO", "Stavordale"},
	{"SVP", "Streatham"},
	{"SVR", "Streatham"},
	{"SWA", "Swansea"},
	{"SWC", "Swanscombe"},
	{"SWD", "Swindon"},
	{"SWE", "Swanley"},
	{"SWI", "Swindon"},
	{"SWK", "Swanwick"},
	{"SWL", "Stwell"},
	{"SWM", "Swanscombe"},
	{"SWN", "Swanage"},
	{"SWO", "Stow"},
	{"SWP", "Swansea"},
	{"SWR", "Swinton"},
	{"SWS", "Swansea"},
	{"SWT", "Swinton"},
	{"SWY", "Sandhurst"},
	{"SYA", "Syon Lane"},
	{"SYB", "Sydenham"},
	{"SYD", "Sydenham"},
	{"SYH", "Syston"},
	{"SYL", "Syon Lane"},
	{"SYN", "Sydenham"},
	{"SYO", "Syston"},
	{"SYS", "Syston"},
	{"TAD", "Tadworth"},
	{"TAL", "Talsarnau"},
	{"TAM", "Tamworth"},
	{"TAN", "Tanygrisian"},
	{"TAT", "Tattenham Corner"},
	{"TAW", "Taunton"},
	{"TBW", "Tibshelf"},
	{"TCR", "Tottenham Court Road"},
	{"TDU", "Todmorden"},
	{"TEA", "Teignmouth"},
	{"TED", "Teddington"},
	{"TEI", "Teignmouth"},
	{"TEM", "Temple Meads"},
	{"TEN", "Tenby"},
	{"TES", "Tees"},
	{"TET", "Teignmouth"},
	{"TFC", "Trafford Centre"},
	{"TFN", "Tiverton Parkway"},
	{"TGM", "Teignmouth"},
	{"THA", "Thalassa"},
	{"THB", "Theale"},
	{"THC", "Thatcham"},
	{"THE", "Theale"},
	{"THH", "Thatcham"},
	{"THI", "Thirsk"},
	{"THL", "Theobalds Grove"},
	{"THN", "Thornton"},
	{"THO", "Thornton Heath"},
	{"THR", "Thirsk"},
	{"THS", "Thatcham"},
	{"THT", "Thornton"},
	{"THW", "Theobalds Grove"},
	{"TIL", "Tilehurst"},
	{"TIP", "Tipton"},
	{"TIV", "Tiverton Parkway"},
	{"TLH", "Tulse Hill"},
	{"TNA", "Tonbridge"},
	{"TNN", "Tonypandy"},
	{"TNP", "Tonbridge"},
	{"TNS", "Tonbridge"},
	{"TOD", "Todmorden"},
	{"TOK", "Tonbridge"},
	{"TON", "Tonbridge"},
	{"TOP", "Tooting"},
	{"TOR", "Torquay"},
	{"TOS", "Tooting"},
	{"TOT", "Totnes"},
	{"TOW", "Tow Law"},
	{"TPB", "Taplow"},
	{"TPN", "Torpantau"},
	{"TPT", "Taplow"},
	{"TPW", "Taplow"},
	{"TRA", "Trallwng"},
	{"TRD", "Tredegar"},
	{"TRF", "Trafford"},
	{"TRH", "Thornton Heath"},
	{"TRI", "Tring"},
	{"TRN", "Tring"},
	{"TRO", "Troon"},
	{"TRR", "Truro"},
	{"TRU", "Truro"},
	{"TRW", "Tring"},
	{"TRY", "Truro"},
	{"TSG", "Tyndrum"},
	{"TSS", "Thatcham"},
	{"TTN", "Tattenham Corner"},
	{"TUH", "Tulse Hill"},
	{"TUL", "Tulse Hill"},
	{"TUN", "Tunbridge Wells"},
	{"TUR", "Turnham Green"},
	{"TVP", "Tiverton Parkway"},
	{"TWI", "Twickenham"},
	{"TWN", "Thornton"},
	{"TWO", "Twickenham"},
	{"TWY", "Twyford"},
	{"TYC", "Tycroes"},
	{"TYG", "Tygwyn"},
	{"TYL", "Tylesley"},
	{"TYN", "Tynemouth"},
	{"TYW", "Tywi"},
	{"UHL", "Upper Halliford"},
	{"UMS", "Umberleigh"},
	{"UNI", "University"},
	{"UPH", "Uphall"},
	{"UPL", "Upton"},
	{"UPM", "Upminster"},
	{"UPT", "Upton"},
	{"VIC", "London Victoria"},
	{"VXH", "Vauxhall"},
	{"WAC", "Walsall"},
	{"WAF", "Wadhurst"},
	{"WAL", "Walthamstow"},
	{"WAM", "Walthamstow"},
	{"WAN", "Wanstead Park"},
	{"WAR", "Warrington"},
	{"WAS", "Waskerley"},
	{"WAT", "London Waterloo"},
	{"WAW", "Watford"},
	{"WBL", "Wrabness"},
	{"WBQ", "Waterbeach"},
	{"WBR", "Windsor & Eton Riverside"},
	{"WBS", "Waterbeach"},
	{"WBT", "West Brompton"},
	{"WBY", "Westbury"},
	{"WCD", "Worcester"},
	{"WCK", "Whinhill"},
	{"WCL", "Westcliff-on-Sea"},
	{"WCM", "Worcester Foregate Street"},
	{"WCN", "Welwyn North"},
	{"WCR", "Worcester"},
	{"WCS", "Westcliff-on-Sea"},
	{"WCX", "Wolverhampton"},
	{"WDB", "Woodbridge"},
	{"WDC", "Windsor & Eton Central"},
	{"WDD", "Widnes"},
	{"WDE", "Windermere"},
	{"WDH", "Worksop"},
	{"WDL", "Woodlesford"},
	{"WDM", "Woodham Ferrers"},
	{"WDN", "Widnes"},
	{"WDO", "Wedgwood"},
	{"WDP", "Woodhouse"},
	{"WDR", "Windsor"},
	{"WDS", "Woodbridge"},
	{"WDT", "Wednesfield"},
	{"WDU", "Wendover"},
	{"WDW", "Windsor"},
	{"WEA", "Wembley"},
	{"WEB", "Wendover"},
	{"WED", "Wednesbury"},
	{"WEI", "Weir"},
	{"WEL", "Wellingborough"},
	{"WEM", "Wembley Central"},
	{"WEN", "Wendover"},
	{"WER", "Weybridge"},
	{"WES", "Westbury"},
	{"WEY", "Weymouth"},
	{"WFH", "Welwyn Garden City"},
	{"WFJ", "Welwyn North"},
	{"WFN", "Welwyn North"},
	{"WFW", "Welwyn Garden City"},
	{"WGA", "Wigan"},
	{"WGC", "Welwyn Garden City"},
	{"WGN", "Wigan"},
	{"WGW", "Wigan"},
	{"WHD", "Whinhill"},
	{"WHG", "Whitchurch"},
	{"WHI", "Whitehaven"},
	{"WHL", "Whimple"},
	{"WHN", "Whitecraigs"},
	{"WHO", "Whitmore"},
	{"WHP", "Whimple"},
	{"WHR", "Whitchurch"},
	{"WHS", "Whitecraigs"},
	{"WHT", "Whitchurch"},
	{"WHY", "Whimple"},
	{"WIC", "Wick"},
	{"WID", "Widnes"},
	{"WIG", "Wigan"},
	{"WIH", "Whitehaven"},
	{"WIL", "Wiltshire"},
	{"WIN", "Winchester"},
	{"WIT", "Witham"},
	{"WIW", "Wickham Market"},
	{"WKD", "Whitecraigs"},
	{"WKF", "Wakefield"},
	{"WKG", "Wokingham"},
	{"WKI", "Wickham"},
	{"WKK", "Whitecraigs"},
	{"WKM", "Wokingham"},
	{"WKN", "Wakefield Kirkgate"},
	{"WKS", "Wakefield Westgate"},
	{"WLD", "Wellingborough"},
	{"WLE", "Walsall"},
	{"WLF", "Woodlesford"},
	{"WLG", "Wellington"},
	{"WLI", "Wolverhampton"},
	{"WLL", "Walsall"},
	{"WLN", "Walton-on-Thames"},
	{"WLP", "Walsall"},
	{"WLR", "Walton-on-Thames"},
	{"WLS", "Walsall"},
	{"WLT", "Walton-on-Thames"},
	{"WLV", "Wolverhampton"},
	{"WLW", "Walsall"},
	{"WLY", "Walsall"},
	{"WMB", "Wembley"},
	{"WMC", "Wombwell"},
	{"WMD", "Wormwood Scrubs"},
	{"WME", "Wimbledon"},
	{"WMG", "Wimbledon"},
	{"WMN", "Wombwell"},
	{"WMP", "Wembley"},
	{"WMS", "Wimbledon"},
	{"WMW", "Wombwell"},
	{"WNA", "Whittlesea"},
	{"WNB", "Wanstead Park"},
	{"WNC", "Windsor & Eton Central"},
	{"WND", "Wanstead"},
	{"WNE", "Whittlesea"},
	{"WNF", "Wanstead Park"},
	{"WNG", "Wanstead"},
	{"WNH", "Whittlesea"},
	{"WNO", "Windsor"},
	{"WNP", "Newport"},
	{"WNS", "Wanstead"},
	{"WNT", "Wantage"},
	{"WNW", "Winsford"},
	{"WOB", "Wool"},
	{"WOC", "Worcester Foregate Street"},
	{"WOF", "Worcester Foregate Street"},
	{"WOH", "Wool"},
	{"WOK", "Woking"},
	{"WOL", "Wolverhampton"},
	{"WOM", "Wombwell"},
	{"WON", "Woolwich"},
	{"WOO", "Woolwich Arsenal"},
	{"WOR", "Worcester"},
	{"WOS", "Worcester Shrub Hill"},
	{"WOT", "Wootton Bassett"},
	{"WPL", "Wapping"},
	{"WRB", "Warrington Bank Quay"},
	{"WRC", "Worcester Foregate Street"},
	{"WRE", "Warrington"},
	{"WRH", "Wrexham"},
	{"WRL", "Warrington"},
	{"WRM", "Wrabness"},
	{"WRN", "Warrington"},
	{"WRO", "Wroxham"},
	{"WRP", "Worksop"},
	{"WRR", "Warrington"},
	{"WRS", "Wrexham General"},
	{"WRT", "Worthing"},
	{"WRU", "Wrexham"},
	{"WRW", "Warrington"},
	{"WRX", "Wrexham"},
	{"WRY", "Worksop"},
	{"WSA", "Weston-super-Mare"},
	{"WSB", "Weston-super-Mare"},
	{"WSE", "Westerhope"},
	{"WSF", "Westhoughton"},
	{"WSG", "West Sutton"},
	{"WSH", "Westhoughton"},
	{"WSM", "Weston-super-Mare"},
	{"WSN", "Weston-super-Mare"},
	{"WSP", "Wasp Green"},
	{"WSR", "Westbury"},
	{"WSS", "Weston-super-Mare"},
	{"WST", "Westcliff-on-Sea"},
	{"WSU", "West Sutton"},
	{"WSW", "Westhoughton"},
	{"WTA", "Watford"},
	{"WTB", "Whitby"},
	{"WTC", "Whitechapel"},
	{"WTG", "Watlington"},
	{"WTH", "Worthing"},
	{"WTJ", "Watford Junction"},
	{"WTL", "Whitley Bay"},
	{"WTM", "Whitmore"},
	{"WTN", "Whitton"},
	{"WTO", "Whitstable"},
	{"WTR", "Watford"},
	{"WTS", "Whitstable"},
	{"WTT", "Watton-at-Stone"},
	{"WTY", "Wentworth"},
	{"WVF", "Watford"},
	{"WVH", "Waterloo"},
	{"WVL", "Westville"},
	{"WVN", "Wolverhampton"},
	{"WVY", "Waverly"},
	{"WWI", "Whitechapel"},
	{"WWR", "Whitwell"},
	{"WXC", "Waxham"},
	{"WYB", "Weybridge"},
	{"WYE", "Wye"},
	{"WYG", "Weybridge"},
	{"WYM", "Weymouth"},
	{"WYN", "Wyn"},
	{"WYT", "Wyther"},
	{"XFL", "Gatwick Airport"},
	{"YAL", "Yalding"},
	{"YAT", "Yate"},
	{"YEO", "Yeovil"},
	{"YEP", "Yeovil Pen Mill"},
	{"YET", "Yeovil"},
	{"YKS", "Yorks"},
	{"YNW", "Ynyswen"},
	{"YOK", "Yoker"},
	{"YOR", "York"},
	{"YRM", "Yarm"},
	{"YRK", "York"},
	{"YSM", "Ystrad Mynach"},
	{"YSR", "Ystrad Rhondda"},
	{"YVJ", "Yeovil Junction"},
	{"ZFD", "Stratford"},
}

// stationByName returns the CRS code for a given station name (case-insensitive).
func stationByName(name string) (string, bool) {
	name = strings.ToLower(name)
	for _, s := range stations {
		if strings.ToLower(s.Name) == name {
			return s.CRS, true
		}
	}
	return "", false
}

// stationName returns the display name for a CRS code.
func stationName(crs string) string {
	for _, s := range stations {
		if s.CRS == crs {
			return s.Name
		}
	}
	return crs
}
